spring:
  application:
    name: Backend-Nhom6
    version: 0.0.1
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/h2db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi/openapi.yaml
    disable-swagger-default-url: true

internal:
  secret: DlSf0vN1kZFz52iozIdi

jwt:
  secret: L9Q7tMNhwcKCB4mRYybxWiG8X/ig97x3n/YAcPI3Pt1mTtpnktT+2giK6T2gBt8pY9ddU5ShYgwIdRQQbVQOjA==
  expiration: 86400000